name: PHPUnit

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php
      with:
        php-version: '8.3'
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Change to backend directory
      run: cd backend
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test