name: PHPUnit

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test_laravel
        ports:
          - 55432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./backend
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./backend
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
      working-directory: ./backend
      env:
        DB_CONNECTION: pgsql
        DB_DATABASE: db_test_laravel
        DB_PORT: 55432
        DB_USERNAME: postgres
        DB_PASSWORD: postgres